dz5-tooltip
js-tasks-ru/htmlcss-20221107_k563ke70 pull request #12
Opened 2022-11-29 15:39 UTC by kir563

2022-11-29 15:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-29 15:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-29 18:14 UTC, GSemikozov requested changes

2022-11-29 18:14 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    top: calc(-100% + -24px);
`bottom: calc(100% + 16px)`

2022-11-29 18:14 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    left: calc(-50% + 24px);
просто -50%, а ниже уже есть transform: translateX(-50%);

2022-11-30 07:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-06 07:17 UTC, GSemikozov approved these changes

2022-12-06 07:17 UTC, merged