D3 accord
js-tasks-ru/htmlcss-20221107_k563ke70 pull request #5
Opened 2022-11-18 06:09 UTC by kir563

2022-11-18 06:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-18 10:42 UTC, GSemikozov requested changes

2022-11-18 10:42 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
марджины на уровне блока не задаем, и в целом по структуре на самом деле это элемент блока, а не блок, например .accordion__item

2022-11-18 10:42 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    display: block;
не хватает стилей текста

2022-11-18 10:42 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-top: 16px;
не хватает стилей для оформления текста

2022-11-19 08:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-20 13:57 UTC, GSemikozov requested changes

2022-11-20 13:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary_font {
эти стили сразу на .accordion__summary, без модификатора

2022-11-20 13:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__content_font {
сразу на .accordion__content

2022-11-21 00:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-21 21:32 UTC, GSemikozov approved these changes

2022-11-21 21:32 UTC, merged